on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

env:
  CARGO_INCREMENTAL: 0

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.7.3

      - name: clippy check
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: compile for unit test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --no-run --locked

      - name: unit test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test

      - name: example build (marubatsu)
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --example simple-marubatsu

      - name: example build (gomoku)
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --example simple-gomoku
